sudo: required
services:
  - docker

script:
  - docker build -t graylog .
  - docker run --name some-mongo -d mongo
  - sleep 10
  - docker run --name some-elasticsearch -d elasticsearch elasticsearch -Des.cluster.name="graylog"
  - sleep 30
  - docker run --link some-mongo:mongo --link some-elasticsearch:elasticsearch --name mygraylog -d graylog
  - docker run --link some-mongo:mongo --link some-elasticsearch:elasticsearch --name nguoianphu-graylog -d nguoianphu/docker-graylog
  - docker ps -a
  # - docker logs -f mygraylog

